### PR TITLE
Add back preprocessor defines to guard libraries

### PR DESCRIPTION
**Pull request by mirh**
I was trying to make an arduino nano every board work with RC.. and well, simply put *Ethercard* is kinda old and unmaintained by now (you may want to check *EthernetENC* perhaps as an alternative, but idk really about the technical merits aside of "age"). 
So, since I'm just fine with serial while excluding it I also took the occasion to satisfy my #11 itch. 

I still kept `useMCP` as a moduleconfig variable, because I'm 100% certain I would have broken/forgot something if I had touched it. 
(but please dispose of it as you like). 

p.s. I also updated .gitignore as a bonus with all the files you usually forget. 
(cleanup of them wouldn't hurt then now, though it would have seemed excessive to proceed with it in this PR)

### CODE REVIEW

**Comment by SK21** [comment]
What prevents the nano every from working? For the nano the existing code works. There are some files that are not needed for usb use, but I don't believe they cause a problem. The concept of the code is to not require users to edit the ino. PCBsetup is used to change the settings. If someone wants to edit the code they can make whatever changes they want.

I will try your changes to gitignore.

**Comment by mirh** [comment]
The every doesn't work due to https://github.com/njh/EtherCard/pull/335 and due to your checkboard code making direct use of 328-specific registers. 

You are absolutely right I had forgotten about the toggles within the application...
I'll move the logic to "support X" (which is going to be true by default of course) rather than "enable X". 

Then it would be cool if RC could detect when the arduino wasn't compiled with the right libraries and grey out buttons (maybe the mcp setting field could be set to -1 to signal this situation?) but I reckon beggars can't be choosers.

**Comment by SK21** [comment]
I have created a new branch with your changes and some modifications. It should still work with the nano every.

**Comment by mirh** [comment]
Yes. 
Though, did you put it in a new branch just to let it soak for testing undisturbed from other concerns?
Or does it mean that you aren't comfortable at all with that going to mainline? (too much visual clutter when reading files?)
Also, why did you go with that code duplication in the SupportMCP23017 ifs, as opposed to my (as dumb as elegant) version?

**Comment by mirh** [comment]
Sure, by all means take even a month if you need/want. 

Speaking of working.. putting aside the fact that [yet](https://github.com/SK21/AOG_RC/issues/15) again it was a nightmare to get the settings to be applied the first time (maybe it was using the old 2.2.0-d configurator to unlock the situation, or maybe it was toggling the atmega328 registers emulation mode in the IDE?) is it normal that \*nothing happens\* unless I disable "Auto" from the switches window?
Maybe my memory is a bit iffy after all this walls I have banged, but I could have swore that it didn't completely nerf all pins with the OG nano.

**Pull request closed without merging**
